import { useAuth } from "@/context/authContext";
import Head from "next/head";
// import Image from "next/image";
// import Link from "next/link";
// import { useRouter } from "next/router";
import React, { FormEvent, useEffect, useState } from "react";
// import VisibilityIcon from "@mui/icons-material/Visibility";
import WithAuth from "@/utils/withAuth";
import LoginForm from "@/components/auth/login";
import ContinueWith from "@/components/auth/continueWith";

function Login() {
   return (
      <div className="min-h-[100vh] h-full bg-lightGray flex flex-col items-center bg-[#fff]">
         <Head>
            <title>Login</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="max-w-[90vw] w-[20rem]">
            <LoginForm />
            <ContinueWith />
         </div>
      </div>
   );
}

export default Login;
