import { useAuth } from "@/context/authContext";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useEffect } from "react";

function VuelvePronto() {
   const { logout } = useAuth();
   useEffect(() => {
      const cerrarsesion = async () => {
         await logout();
      };
      cerrarsesion();
   }, [logout]);

   return (
      <div className="min-h-[100vh] h-full  flex flex-col items-center bg-[#f5f5f5]">
         <Head>
            <title>Vuelve Pronto!</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Link href="/auth/login" className="w-full max-w-sm my-auto">
            <span className="relative flex aspect-[24/9] w-full max-w-sm ">
               <Image src="/BellezaSanaBannerCropped.png" alt="" fill />
            </span>
         </Link>
      </div>
   );
}

export default VuelvePronto;
