import React, { FormEvent, useEffect, useState } from "react";
import { useAuth } from "@/context/authContext";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Image from "next/image";
import VisibilityIcon from "@mui/icons-material/Visibility";
import RegisterForm from "@/components/auth/register";
import ContinueWith from "@/components/auth/continueWith";

function Registro() {
   return (
      <div className="min-h-[100vh] h-full bg-lightGray flex flex-col items-center bg-[#fff]">
         <Head>
            <title>Registro</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="max-w-[90vw] w-[20rem]">
            <RegisterForm />
            <ContinueWith />
         </div>
      </div>
   );
}

export default Registro;
