import React, { FormEvent, useEffect, useState } from "react";
import { useAuth } from "@/context/authContext";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Image from "next/image";
import VisibilityIcon from "@mui/icons-material/Visibility";

function Registro() {
   const [name, setName] = useState("");
   const [email, setEmail] = useState("");
   const [password, setPassword] = useState("");
   const [confirmPassword, setConfirmPassword] = useState("");
   const [error, setError] = useState("");
   const [showPassword, setShowPassword] = useState(false);
   const [showConfirmPassword, setShowConfirmPassword] = useState(false);
   const { loginWithGoogle, createUserWithEmail, currentUser } = useAuth();

   const router = useRouter();

   useEffect(() => {
      if (currentUser) {
         router.push("/");
      }
   }, [router, currentUser]);

   const registerUser = async (e: FormEvent) => {
      e.preventDefault();

      if (password !== confirmPassword) {
         setError("Las contraseñas no coinciden");
         return;
      }

      let signInError = await createUserWithEmail(email, password);

      if (signInError) {
         signInError = signInError.split(":")[1].split("(")[0];
         setError(signInError);
         console.log(signInError);
         return;
      }

      setName("");
      setEmail("");
      setPassword("");
      setConfirmPassword("");
   };

   return (
      <div className="min-h-[100vh] h-full bg-lightGray flex flex-col items-center">
         <Head>
            <title>Registro</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="px-4 pt-4 mt-4 bg-white rounded-lg max-w-[90vw] w-[24rem]">
            <div className="flex flex-col items-center w-full ">
               <div
                  className={`${
                     error === "" ? "hidden" : "flex"
                  } w-[90%] bg-[#ffc0c0]  justify-center`}
               >
                  <p className="p-1 text-sm text-black">{error}</p>
               </div>
               <h1 className="mb-4 text-3xl font-bold">Registrate</h1>

               <form
                  onSubmit={registerUser}
                  className="flex flex-col items-start w-full"
               >
                  <div className="inputBox">
                     <label htmlFor="name">Nombre Completo:</label>
                     <input
                        type="text"
                        name="name"
                        placeholder="Nombre Completo"
                        required
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                     />
                  </div>
                  <div className="inputBox">
                     <label htmlFor="email">Correo:</label>
                     <input
                        type="text"
                        name="email"
                        placeholder="Correo Electronico"
                        required
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                     />
                  </div>
                  <div className="inputBox">
                     <label htmlFor="pass">Contraseña:</label>
                     <span className="flex items-center">
                        <input
                           type={`${showPassword ? "text" : "password"}`}
                           name="pass"
                           placeholder="Contraseña"
                           required
                           value={password}
                           onChange={(e) => setPassword(e.target.value)}
                        />
                        <VisibilityIcon
                           onClick={() => setShowPassword((show) => !show)}
                           className="text-[#aaa] hover:text-[#555] cursor-pointer"
                        />
                     </span>
                  </div>
                  <div className="inputBox">
                     <label htmlFor="pass">Confirmar Contraseña:</label>
                     <span className="flex items-center">
                        <input
                           type={`${showConfirmPassword ? "text" : "password"}`}
                           name="pass"
                           placeholder="Confirmar Contraseña"
                           required
                           value={confirmPassword}
                           onChange={(e) => setConfirmPassword(e.target.value)}
                        />
                        <VisibilityIcon
                           onClick={() =>
                              setShowConfirmPassword((show) => !show)
                           }
                           className="text-[#aaa] hover:text-[#555] cursor-pointer"
                        />
                     </span>
                  </div>

                  <div className="w-[90%] flex flex-col items-center mx-auto">
                     <button
                        type="submit"
                        className="w-full p-2 mt-2 text-white bg-buttonBlue rounded-3xl hover:scale-[1.005]"
                     >
                        Enviar
                     </button>
                     <button
                        type="button"
                        onClick={loginWithGoogle}
                        className="flex items-center justify-center w-full py-2 border-2 rounded-3xl hover:scale-[1.005] mt-1"
                     >
                        <span className="relative flex h-6 mr-4 aspect-square">
                           <Image
                              src="/socialMediaIcons/google.png"
                              alt="Google icon"
                              fill
                           />
                        </span>
                        <p>Continua con Google</p>
                     </button>
                  </div>
               </form>
            </div>
            <div className="flex gap-1 p-4 text-sm">
               <p>¿Tienes una cuenta?</p>
               <Link href="/login" className="text-blue-400 underline">
                  Inicia sesion
               </Link>
            </div>
         </div>
      </div>
   );
}

export default Registro;
